version: '3.8'

services:   
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        NODE_ENV: production
        FORMATTER_TIME: DD-MM-YYYY HH:mm:ss
        BACKEND_URL: http://localhost:5000
        PORT: 5000
        TZ: America/Sao_Paulo
        API_KEY: gmOcM3kO1AYkwzoFFZ96K87FZTa2c7qG
    ports:
      - "5000:5000"
    networks:
      - network

networks:
  network:
    driver: bridge
